class HomeLocators:
    LEFT_BAR = ".left-sidebar"
    LEFT_BAR_CATEGORY_TITLES=".panel-title"
    LEFT_BAR_SUB_CATEGORY_TITLES=".panel-body a"
    LEFT_BAR_BRAND_NAMES=".brands-name li"
    FEATURE_ITEMS_BLOCK=".features_items"
    FEATURE_ITEMS_BLOCK_TITLE=".features_items .title"
    PRODUCT_BLOCKS=".features_items .product-image-wrapper"
    VIEW_PRODUCT_BUTTONS=".choose a"
    ADD_TO_CART_PRODUCT_BUTTONS=".single-products a"
    PRODUCT_ITEMS=".single-products a"
    ADD_TO_CART_OVERLAY_BUTTONS=".overlay-content a"
